apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-gateway
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cilium-gateway
  source:
    repoURL: https://github.com/ealoltm/k8s-gitops.git
    targetRevision: main
    path: platform/ingress/cilium-gateway/base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
