apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ealoltm/k8s-gitops.git
    targetRevision: main
    path: platform/ingress/cilium-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: cilium-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
