---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kube-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.10.10.200-10.10.10.250

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: kube-l2adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - kube-pool
