apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: 0.9.1
    helm:
      releaseName: argocd-image-updater
      values: |
        argocd:
          serverAddress: http://argocd-server.argocd.svc.cluster.local:80
        config:
          registries:
            - name: docker
              api_url: https://registry-1.docker.io
              credentials: secret:argocd/docker-credentials
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
